import KS1 from "../assets/ks1-2.webp";
import KS2 from "../assets/ks2.jpg";
import KS3 from "../assets/KS3.jpg";
import KS4 from "../assets/KS4.jpg";
import KS5 from "../assets/KS5.jpg";
import KS6 from "../assets/TTCHotel.jpg";
import KS7 from "../assets/KS7.jpg";
import KS8 from "../assets/KS8.jpg";

export const MenuHotel = [
    {
        image: KS1,
        nameHotel: "La Vela Saigon Hotel",
        overView: "Nằm ở TP. Hồ Chí Minh, cách Chợ Tân Định 8 phút đi bộ, La Vela Saigon Hotel cung cấp chỗ nghỉ có hồ bơi ngoài trời, chỗ đậu xe riêng miễn phí, trung tâm thể dục và phòng chờ chung. Ngoài Wi-Fi miễn phí, khách sạn 5 sao này còn cung cấp dịch vụ phòng và quầy lễ tân 24 giờ. Khách sạn có sân hiên và nhìn ra thành phố, ngoài ra du khách có thể thưởng thức bữa ăn tại nhà hàng hoặc đồ uống tại quầy bar.",
        price: "219",
        location: "Hồ Chí Minh",
        detailLocation: "280 Nam Ky Khoi Nghia, Ward 8, District 3, Quận 3, TP. Hồ Chí Minh, Việt Nam",
        review: "4.8",
        textReview: "Very Good",
        numReview: "817",
        url: "https://www.booking.com/hotel/vn/la-vela-saigon.vi.html?aid=2276380&label=msn-JZxagb2X0Y90e0b%2A9IfB2Q-80539376755312%3Atikwd-80539531655927%3Aloc-166%3Aneo%3Amte%3Alp153408%3Adec%3AqsLa%20Vela%20Saigon%20Hotel&sid=fb24a1976c82904f268151da3097bb0e&dest_id=-3730078&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1739899066&srpvid=faf379902d8a0116&type=total&ucfs=1&",
    },
    {
        image: KS2,
        nameHotel: "22 Homestay Đà Lạt",
        overView: "Tọa lạc ở Đà Lạt và cách Vườn hoa Đà Lạt 4.4 km, 22 Homestay Đà Lạt - A Member Of Nhà Sói có khu vườn, các phòng không hút thuốc và Wi-Fi miễn phí. Chỗ nghỉ cách Hồ Xuân Hương khoảng 4.8 km, Công viên Yersin 4.8 km và Quảng trường Lâm Viên 5 km. Thiền Viện Trúc Lâm cách khách sạn 11 km và Núi Lang Bian 22 km. Tất cả các căn ở khách sạn được trang bị ấm đun nước. Mỗi phòng đều được thiết kế có điều hòa và TV màn hình phẳng, ngoài ra một số căn tại 22 Homestay Đà Lạt - A Member Of Nhà Sói có ban công. Phòng khách có ga trải giường.",
        price: "120",
        location: "Đà Lạt",
        detailLocation: "22 Đường Nam Hồ, 66100 Đà Lạt, Việt Nam",
        review: "3.7",
        textReview: "Good",
        numReview: "36",
        url: "https://www.booking.com/hotel/vn/22-house-dalat.vi.html?aid=357029&label=yho748jc-1FCAso9AFCDjIyLWhvdXNlLWRhbGF0SCpYA2j0AYgBAZgBKrgBF8gBDNgBAegBAfgBAogCAagCA7gCtofTvQbAAgHSAiQ0ZTZjNzBmZi04MGY5LTRjYzItOGUwOS01YTZiZTE4NDgwN2bYAgXgAgE&sid=fb24a1976c82904f268151da3097bb0e&dest_id=-3712045&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1739899848&srpvid=09987b1ba7ca0279&type=total&ucfs=1&",
      },
      {
        image: KS3,
        nameHotel: "Nesta Hotel",
        overView: "Nằm ở thành phố Cần Thơ, dọc theo Sông Hậu, Nesta Hotel Can Tho có nhà hàng. Truy cập Wi-Fi được cung cấp miễn phí trong toàn bộ khách sạn. Được trang trí độc đáo, mỗi phòng nghỉ ở đây đều có truyền hình cáp màn hình phẳng, máy lạnh và minibar. Ngoài ra còn được trang bị ấm đun nước điện. Phòng tắm riêng đi kèm máy sấy tóc, đồ vệ sinh cá nhân miễn phí và dép. Một số phòng nhìn ra quang cảnh Sông Hậu hoặc thành phố. Nesta Hotel Can Tho có lễ tân 24 giờ, khu vườn và quầy bar. Dịch vụ đặt vé và chỗ để hành lý cũng nằm trong số các tiện ích ở đây. Khách sạn còn cung cấp chỗ đỗ xe miễn phí.",
        price: "199",
        location: "Cần Thơ",
        detailLocation: "9C Tran Phu, Cần Thơ, Việt Nam",
        review: "3.5",
        textReview: "Good",
        numReview: "100",
        url: "https://www.booking.com/hotel/vn/nesta.vi.html?aid=2276380&label=msn-JjJ17FhB98Y8LrgCZz6VLQ-80539376725623%3Atikwd-80539531679965%3Aloc-166%3Aneo%3Amte%3Alp153408%3Adec%3AqsNesta%20Hotel&sid=fb24a1976c82904f268151da3097bb0e&dest_id=-3709910&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1739899914&srpvid=21417b43ea6606a8&type=total&ucfs=1&",
      },
      {
        image: KS4,
        nameHotel: "Le Pont Mu Waterfall",
        overView: "Nằm ở Ải Hạ, Le Pont Mu Waterfall Homestay có khu vườn, nhà hàng, quầy bar, cùng Wi-Fi miễn phí ở toàn bộ chỗ nghỉ. Chỗ nghỉ này cung cấp dịch vụ phòng và quầy lễ tân 24 giờ cho khách. Tất cả các phòng ở khách sạn được trang bị ấm đun nước. Các phòng đều có phòng tắm riêng với vòi xịt/chậu rửa vệ sinh, đồ vệ sinh cá nhân miễn phí và máy sấy tóc. Tại Le Pont Mu Waterfall Homestay, mỗi phòng đều được thiết kế có ga trải giường và khăn tắm. Sân bay gần nhất là Sân bay Thọ Xuân, cách chỗ nghỉ 99 km.",
        price: "139",
        location: "Ải Hạ",
        detailLocation: "Xã Tự Do, huyện Lạc Sơn, tỉnh Hòa Bình, Ải Hạ, Việt Nam",
        review: "4.2",
        textReview: "Very Good",
        numReview: "13",
        url: "https://www.booking.com/hotel/vn/lepont-mu-waterfall-bungalow.vi.html?aid=357029&label=yho748jc-1FCAso9AFCHGxlcG9udC1tdS13YXRlcmZhbGwtYnVuZ2Fsb3dIM1gDaPQBiAEBmAEquAEXyAEM2AEB6AEB-AEMiAIBqAIDuAKgiNO9BsACAdICJGY2MjRlZjY1LWYxMjktNGIxZC05NWNhLTRkZjQwZDlkZDQ0MdgCBuACAQ&sid=fb24a1976c82904f268151da3097bb0e&dest_id=-3715295&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1739899942&srpvid=9a3a7b518a980083&type=total&ucfs=1&",
      },
      {
        image: KS5,
        nameHotel: "Vinpearl Resort & Spa",
        overView: "Chào đón du khách với kiến trúc mái ngói đỏ tươi đậm chất Đông Dương và hồ bơi ngoài trời rộng gần 5.000m2 ôm trọn khuôn viên khu nghỉ dưỡng, Vinpearl Resort & Spa Phu Quoc mang đến hành trình trải nghiệm ngập tràn hương sắc thiên nhiên đặc trưng của đảo ngọc. Du khách có thể vừa dạo bước trên bãi biển vừa ngắm “bữa tiệc ánh sáng” rực rỡ phía chân trời, cảm giác sảng khoái và hạ nhiệt ngay lập tức khi đặt chân vào khuôn viên xanh mát nơi đây sau một ngày dài khám phá hay thả mình trên chiếc ghế lười xem một bộ phim yêu thích của gia đình tại rạp chiếu phim trên bãi biển. Những trải nghiệm không thể bỏ qua tại đây bao gồm thưởng thức tiệc buffet hải sản với nhạc sống và ngắm cảnh hoàng hôn tuyệt đẹp tại nhà hàng Pepper bên bờ biển cũng như tận hưởng liệu pháp mát-xa kiểu Bali độc đáo tại túp lều spa giữa khung cảnh yên bình. Vinpearl Resort & Spa Phu Quoc cung cấp chỗ nghỉ hiện đại và sang trọng với Wi-Fi miễn phí trong toàn bộ khuôn viên và hồ bơi ngoài trời cũng như khu vực bãi biển riêng. Chỗ nghỉ này có lễ tân 24 giờ, dịch vụ văn phòng và tiện nghi tổ chức tiệc/hội họp.",
        price: "291",
        location: "Phú Quốc",
        detailLocation: "Bai Dai, Ganh Dau, Ganh Dau, Phú Quốc, Việt Nam",
        review: "4.6",
        textReview: "Very Good",
        numReview: "893",
        url: "https://www.booking.com/hotel/vn/vinpearl-resort-phu-quoc.vi.html?aid=357029&label=yho748jc-1FCAso9AFCGHZpbnBlYXJsLXJlc29ydC1waHUtcXVvY0gzWANo9AGIAQGYASq4ARfIAQzYAQHoAQH4AQyIAgGoAgO4Ar-I070GwAIB0gIkZGFlOGE2NjEtMjhkYy00OTllLWExZjktMDZkNzY1NTdiMTc12AIG4AIB&sid=fb24a1976c82904f268151da3097bb0e&dest_id=-3726177&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1739899972&srpvid=00c57b6015fb067e&type=total&ucfs=1&",
      },
      {
        image: KS6,
        nameHotel: "TTC Hotel - Cần Thơ",
        overView: "Tận hưởng dịch vụ đỉnh cao, đẳng cấp thế giới tại TTC Hotel - Can Tho. Nằm trên bờ Sông Hậu và cách bờ sông 2 phút đi bộ, TTC Hotel -  Can Tho tọa lạc ở trung tâm thành phố Cần Thơ. Với tầm nhìn ra toàn cảnh thành phố và dòng sông, khách sạn 10 tầng này có hồ bơi ngoài trời, lễ tân 24 giờ và Wi-Fi miễn phí trong toàn bộ khuôn viên. TTC Hotel -  Can Tho nằm cách Chùa Ông, Chợ Đêm và Sân vận động Cần thơ 500 m. Chỗ nghỉ nằm trong bán kính chỉ 6 km từ chợ nổi Cái Răng và 7 km từ sân bay Cần Thơ. Thành phố Hồ Chí Minh cách đó khoảng 3 giờ lái xe. Phòng nghỉ lắp máy điều hòa tại đây có sàn lát gạch và được trang bị đầy đủ tiện nghi với tủ để quần áo, bàn làm việc, truyền hình cáp và khu vực ghế ngồi. Trong phòng cũng có minibar và tiện nghi pha trà/cà phê. Phòng tắm riêng được bố trí máy sấy tóc, áo choàng tắm và đồ vệ sinh cá nhân miễn phí.",
        price: "130",
        location: "Cần Thơ",
        detailLocation: "2 Hai Bà Trưng, Tân An, Ninh Kiều, Cần Thơ, Việt Nam",
        review: "4.5",
        textReview: "Very Good",
        numReview: "875",
        guests: "3 guests",
        url: "https://www.booking.com/hotel/vn/golf-can-tho.vi.html?aid=2276374&label=msn-PyFJE5Vv6aBTiZIo%2AmQarQ-80195767927651%3Atikwd-80195916640542%3Aloc-166%3Aneo%3Amte%3Alp153408%3Adec%3AqsTTC%20Hotel%20Th%C6%A1&sid=fb24a1976c82904f268151da3097bb0e&dest_id=-3709910&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1739899998&srpvid=e19c7b6d4e5f0293&type=total&ucfs=1&",
    },
    {
        image: KS7,
        nameHotel: "Mường Thanh Luxury",
        overView: "Muong Thanh Luxury Ca Mau Hotel cung cấp chỗ ở tại tỉnh Cà Mau và có Wi-Fi miễn phí, nhà hàng cũng như hồ bơi ngoài trời mở cửa quanh năm. Khách sạn cũng có trung tâm spa cùng bồn tắm nước nóng và khách có thể thưởng thức đồ uống tại quầy bar. Mỗi phòng nghỉ tại khách sạn này đều được trang bị máy lạnh và TV truyền hình cáp màn hình phẳng. Du khách sẽ tìm thấy ấm đun nước trong phòng. Các phòng còn đi kèm phòng tắm riêng. Dép, đồ vệ sinh cá nhân miễn phí và máy sấy tóc cũng được cung cấp để mang lại sự thoải mái cho khách.Khách có thể tìm thấy cửa hàng cắt tóc ngay trong khuôn viên. Khách có thể chơi tennis tại khách sạn. Sân bay Rạch Giá cách đó 84 km. Khách sạn cung cấp dịch vụ đón khách miễn phí từ sân bay.",
        price: "200",
        location: "Cà Mau",
        detailLocation: "Lô C3A, Khu Trung tâm hành chính chính trị, Phường 9, Cà Mau, Việt Nam",
        review: "4.6",
        textReview: "Very Good",
        numReview: "420",
        guests: "4 guests",
        url: "https://www.booking.com/hotel/vn/muong-thanh-luxury-ca-mau.vi.html?aid=2276380&label=msn-qEoQ4s2Krxb43QpES4Cd9A-80539376722277%3Atikwd-80539531655434%3Aloc-166%3Aneo%3Amte%3Alp153408%3Adec%3AqsKh%C3%A1ch%20s%E1%BA%A1n%20M%C6%B0%E1%BB%9Dng%20Thanh%20Luxury%20C%C3%A0%20Mau&sid=662009a60db39167233cea122a8a1913&age=0&all_sr_blocks=177795001_392373638_2_1_0_289122&checkin=2025-02-25&checkout=2025-02-26&dest_id=-3709670&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&highlighted_blocks=177795001_392373638_2_1_0_289122&hpos=1&matching_block_id=177795001_392373638_2_1_0_289122&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&sr_pri_blocks=177795001_392373638_2_1_0_289122_121500000&srepoch=1739897118&srpvid=2a5475cdfaa30480&type=total&ucfs=1&",
    },
    {
        image: KS8,
        nameHotel: "Sài Gòn Rạch Giá",
        overView: "Sai Gon Rach Gia Hotel có hồ bơi ngoài trời, trung tâm thể dục, khu vườn và phòng chờ chung ở Rạch Giá. Ngoài Wi-Fi miễn phí, khách sạn 4 sao này còn cung cấp dịch vụ đưa đón miễn phí và dịch vụ phòng. Khách sạn có sân hiên và nhìn ra thành phố, ngoài ra du khách có thể thưởng thức bữa ăn tại nhà hàng hoặc đồ uống tại quầy bar. Khách sạn sẽ cung cấp cho khách các phòng được trang bị điều hòa có bàn làm việc, máy pha cà phê, tủ lạnh, máy rửa bát, két an toàn, TV màn hình phẳng và phòng tắm riêng với vòi xịt/chậu rửa vệ sinh. Tại Sai Gon Rach Gia Hotel, các phòng đều đi kèm với ga trải giường và khăn tắm. Khách tại chỗ nghỉ có thể thưởng thức bữa sáng thực đơn buffet. Sai Gon Rach Gia Hotel có sân chơi trẻ em. Khách có thể chơi bóng bàn tại khách sạn. Ngoài ra, chỗ nghỉ có dịch vụ thuê ô tô. Đội ngũ nhân viên của Sai Gon Rach Gia Hotel luôn túc trực tại lễ tân 24/24 để cung cấp đề xuất cho du khách. Chỗ nghỉ cách Bến Tàu Rạch Giá - Phú Quốc 5.2 km và Chùa Tam Bảo 3.3 km.",
        price: "140",
        location: "Kiên Giang",
        detailLocation: "844 Nguyễn Trung Trực, An Hoà, Rạch Giá, Kiên Giang, Việt Nam",
        review: "4.4",
        textReview: "Very Good",
        numReview: "389",
        guests: "4 guests",
        url: "https://www.booking.com/hotel/vn/sai-gon-rach-gia.vi.html?aid=2276380&label=msn-N54n2tyIxMI0Po6s9dTmQw-80745535232172%3Atikwd-80745689975099%3Aloc-166%3Aneo%3Amte%3Alp153408%3Adec%3AqsKh%C3%A1ch%20s%E1%BA%A1n%20S%C3%A0i%20G%C3%B2n%20R%E1%BA%A1ch%20Gi%C3%A1&sid=662009a60db39167233cea122a8a1913&age=0&all_sr_blocks=140990102_0_2_1_0&checkin=2025-02-25&checkout=2025-02-26&dest_id=-3727643&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&highlighted_blocks=140990102_0_2_1_0&hpos=1&matching_block_id=140990102_0_2_1_0&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&sr_pri_blocks=140990102_0_2_1_0__83075504&srepoch=1739897313&srpvid=7219762ef70702bc&type=total&ucfs=1&",
    }
];